# Generated by Django 5.2.8 on 2025-11-28 17:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('app_key', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='App key can only contain letters, numbers, and underscores', regex='^[a-zA-Z0-9_]+$')])),
                ('description', models.TextField(blank=True)),
                ('fcm_server_key', models.TextField(blank=True, help_text='Firebase Server Key')),
                ('apns_cert_path', models.TextField(blank=True, help_text='Path to APNs certificate')),
                ('apns_topic', models.CharField(blank=True, help_text='APNs topic for push notifications', max_length=255)),
                ('web_vapid_public_key', models.TextField(blank=True, help_text='Web VAPID public key')),
                ('web_vapid_private_key', models.TextField(blank=True, help_text='Web VAPID private key')),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit', models.IntegerField(default=1000, help_text='Max notifications per minute')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'push_apps',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_token', models.TextField(help_text='Push notification token', unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=20)),
                ('user_identifier', models.CharField(help_text='Unique identifier for the user within the app', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('push_token_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.app')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'push_devices',
                'unique_together': {('app', 'user_identifier', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique identifier for the template within the app', max_length=255, validators=[django.core.validators.RegexValidator(message='Template name can only contain letters, numbers, and underscores', regex='^[a-zA-Z0-9_]+$')])),
                ('title_template', models.TextField(help_text='Template for notification title with placeholders')),
                ('body_template', models.TextField(help_text='Template for notification body with placeholders')),
                ('subject_template', models.TextField(blank=True, help_text='Template for email subject (if applicable)')),
                ('data_template', models.JSONField(blank=True, default=dict, help_text='Additional data to send with the notification')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1, help_text='Template version number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='api.app')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'push_templates',
                'unique_together': {('app', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SendLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('subject', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('raw_request', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered'), ('read', 'Read')], default='pending', max_length=20)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='api.app')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='api.device')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_logs', to='api.template')),
            ],
            options={
                'verbose_name': 'Send Log',
                'verbose_name_plural': 'Send Logs',
                'db_table': 'push_send_logs',
                'indexes': [models.Index(fields=['app', 'created_at'], name='push_send_l_app_id_f80dfc_idx'), models.Index(fields=['status', 'created_at'], name='push_send_l_status_8d73d1_idx'), models.Index(fields=['device', 'created_at'], name='push_send_l_device__b5e7e8_idx')],
            },
        ),
    ]
